### ISSUE TITLE
Pillow版本要求应更为严格

### ISSUE THREAD

**Issue by KingRayCao** [noneplugin/nonebot-plugin-wordle#12]
据测试Pillow 10.0.0中`FreeTypeFont`对象删除了`getsize`方法，将会导致`data_source.py`第64行报错`AttributeError: 'FreeTypeFont' object has no attribute 'getsize'`，将Pillow版本回滚到9.5.0可解决这个问题。
请考虑修改Pillow版本要求，或者重构此处代码

**Comment by MeetWq** [comment]
已修复
