### ISSUE TITLE
无法使用wordle

### ISSUE THREAD

**Issue by KeepNaivety3** [noneplugin/nonebot-plugin-wordle#15]
Python版本3.12+新安装的nonebot2+Lagrange.Core，无法使用wordle指令，试过@+/wordle和@+wordle都不行。

问题我觉得可能是alconna+to_me()的问题？rule里去掉to_me()后使用/wordle就正常了
```
wordle = on_alconna(
    Alconna(
        "wordle",
        Option("-l|--length", Args["length", int], help_text="单词长度"),
        Option("-d|--dictionary", Args["dictionary", str], help_text="词典"),
    ),
    aliases=("猜单词",),
    rule=game_not_running,
    use_cmd_start=True,
    block=True,
    priority=13,
)
```

**Comment by MeetWq** [comment]
目前的 wordle 指令也要加@
我试了 @+wordle 是可以的呀
你试试 @+猜单词 行不行？

**Comment by KeepNaivety3** [comment]
查了一下是我的问题，用Tim发送的消息，nonebot只能识别出'[at:qq=0]'. 用QQ发送就正常了。。。
https://github.com/KonataDev/Lagrange.Core/issues/329
