### ISSUE TITLE
【配置请求】能否回滚to_me配置项

### ISSUE THREAD

**Issue by Tosd0** [noneplugin/nonebot-plugin-wordle#16]
突然发现在v0.4.1的时候，to_me的规则发生了重大的改变。之前是可以不用艾特bot的，现在必须艾特才能发起新游戏，所以想问问能不能改回来（泪）感觉每次开启都要艾特还是挺伤的 之前那个规则处理的就挺人性
实在不行再加个配置项？（泪）谢谢了
这个是之前的处理方法：
<img width="695" alt="image" src="https://github.com/noneplugin/nonebot-plugin-wordle/assets/65720409/b095c796-5a31-4273-a329-4014d142b358">

**Comment by MeetWq** [comment]
改了，可以试一下
