### ISSUE TITLE
[ERROR]无法导入indexer

### ISSUE THREAD

**Issue by FLY1919** [noneplugin/nonebot-plugin-wordle#18]
indexer库无法导入
pip 且无法安装
原因:indexer过于老旧
建议更换新的
![Screenshot_20241001_192246](https://github.com/user-attachments/assets/183278cd-cd7d-436c-92ca-ec7250553520)
![Screenshot_20241001_193049](https://github.com/user-attachments/assets/1bdc5c4d-ddda-4cd7-8d54-d6a3d5925da0)
![Image_1727783380237](https://github.com/user-attachments/assets/65c50f35-8e08-4c3a-ade8-b81334ec3643)

**Comment by FLY1919** [comment]
> indexer库无法导入 pip 且无法安装 原因:indexer过于老旧 建议更换新的 ![Screenshot_20241001_192246](https://private-user-images.githubusercontent.com/123441910/372454953-183278cd-cd7d-436c-92ca-ec7250553520.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODM2OTcsIm5iZiI6MTcyNzc4MzM5NywicGF0aCI6Ii8xMjM0NDE5MTAvMzcyNDU0OTUzLTE4MzI3OGNkLWNkN2QtNDM2Yy05MmNhLWVjNzI1MDU1MzUyMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMTQ5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDkxYzZhNjAzMmEyMWI2MDM4YjkyMzAwMjk5ZWE2NmVlOTljMWQ4MWMwYjYyZjdlY2Y5Y2Q5YjljYmNhNWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1LS4pq9n4L31RmzoOxhoSRH5DT6CBDMOYgR8-W0jVzA) ![Screenshot_20241001_193049](https://private-user-images.githubusercontent.com/123441910/372454973-1bdc5c4d-ddda-4cd7-8d54-d6a3d5925da0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODM2OTcsIm5iZiI6MTcyNzc4MzM5NywicGF0aCI6Ii8xMjM0NDE5MTAvMzcyNDU0OTczLTFiZGM1YzRkLWRkZGEtNGNkNy04ZDU0LWQ2YTNkNTkyNWRhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMTQ5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTNjN2M5NTBiOGJhNGNhOTU5MDFkZmQ5MTJkM2RmY2Y4ZmIxYTk4NGZiZWE2NTA4YjMwMzBhNTBjYTk2MDI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oIul4aJyo_ELx3cluZrfoUWpn6qNQu41sJYZkkQ8uxo) ![Image_1727783380237](https://private-user-images.githubusercontent.com/123441910/372455203-65c50f35-8e08-4c3a-ade8-b81334ec3643.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODM2OTcsIm5iZiI6MTcyNzc4MzM5NywicGF0aCI6Ii8xMjM0NDE5MTAvMzcyNDU1MjAzLTY1YzUwZjM1LThlMDgtNGMzYS1hZGU4LWI4MTMzNGVjMzY0My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMTQ5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzg3NjUxNTgwYjYxZmYzZTAzNDdmNTczOGNiMTMyNzhkMzM5NTcxNjdjMjZhNmUwYTAwZGYwZjI4Y2IzZWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.roVgQlk8lQHu0qdXSzSVVQxbJy5tw0T88mDnCtO9pYo)

中间的图片发错了
~~我是傻逼~~)

**Comment by MeetWq** [comment]
你应该装 `pyspellchecker` 而不是 `spellchecker`

**Comment by FLY1919** [comment]
> 你应该装 `pyspellchecker` 而不是 `spellchecker`

啊
好的，已解决))))
~~我简直太傻逼了(~~
