### ISSUE TITLE
关于未被识别的单词

### ISSUE THREAD

**Issue by shmilyty** [noneplugin/nonebot-plugin-wordle#2]
![image](https://user-images.githubusercontent.com/61276699/160312933-bce00688-e627-4150-b8a7-74e6387ca5ad.png)

![image](https://user-images.githubusercontent.com/61276699/160312964-58fd0ddd-c5e2-403f-a27f-788c6ec9b224.png)

这是出了什么问题捏

**Comment by shmilyty** [comment]
还有能不能支持私聊wordle，目前貌似只能在群聊里使用

**Comment by MeetWq** [comment]
我这边试了tumor是可以识别的，你更新到最新版试试?
另外最新版应该私聊可以用了

**Comment by shmilyty** [comment]
更新了一下，现在可以私聊 wordle 了，谢谢您

但是貌似有时候私聊wordle会报错，导致整个wordle瘫痪（不管是在群里还是在私聊里）

bot.py报错如下：

![image](https://user-images.githubusercontent.com/61276699/160323178-34604d48-734e-4c3d-89a7-cf4027725394.png)

场景：在一个群里和一个私聊里同时使用wordle

私聊一开始是可以的，但是在猜到最后一个词的时候整个就寄了，重启一次后群里可以用，但是尝试在私聊里继续游戏时就又报错了。

![image](https://user-images.githubusercontent.com/61276699/160323362-b49db7b0-cc87-4e19-b830-902b8c2ff18e.png)

能提供一下解决方案吗/wq

**Comment by MeetWq** [comment]
逝世现在的

**Comment by shmilyty** [comment]
完全没有问题了
谢谢您！
突然发现自己用的绝大多数插件都是您写的欸

**Comment by shmilyty** [comment]
很抱歉再次打扰，但是好像正常运行了一段时间后又出现了同样的问题（悲）

![image](https://user-images.githubusercontent.com/61276699/160332085-73374b0e-cdd4-4831-9f6c-c05849b0e79c.png)
这个是之后进行的一场正常游戏，但是其他部分好友是不成功的
![image](https://user-images.githubusercontent.com/61276699/160332175-b3690e1a-965c-415e-aae1-dd4aef6dbc90.png)
![image](https://user-images.githubusercontent.com/61276699/160332206-e0128d2f-7c68-4a38-960c-1a3a9058c0d8.png)
同时有如下报错：
![image](https://user-images.githubusercontent.com/61276699/160327319-f9f061f4-6f0c-43bc-8dff-c64da0178e16.png)
可能这个报错出现了很多次~~因为时间对不上~~

麻烦您了

**Comment by MeetWq** [comment]
最新版不应该有这个报错才对，你检查一下是不是 0.1.5.1 版

**Comment by shmilyty** [comment]
ok了
