### ISSUE TITLE
总是找不到单词，例如mold,honor

### ISSUE THREAD

**Issue by MeetWq** [noneplugin/nonebot-plugin-wordle#3]
另外您的wordle老是找不到单词，更新最新版也没用，例如mold,honor，但是答案又是这些单词（

_Originally posted by @863109569 in https://github.com/MeetWq/nonebot-plugin-petpet/issues/45#issuecomment-1080804994_

**Comment by MeetWq** [comment]
@863109569 看看 pyenchant 版本

**Comment by LucyChao233** [comment]
> @863109569 看看 pyenchant 版本

3.2.2

**Comment by MeetWq** [comment]
```
>>> import enchant
>>> en_dict = enchant.Dict("en")
>>> en_dict.check("honor")
True
```

试试直接在python下调用，看看结果

**Comment by 863109569** [comment]
> 

false

**Comment by LucyChao233** [comment]
> Owner

false

**Comment by LucyChao233** [comment]
![image](https://user-images.githubusercontent.com/77315378/160586372-2babc060-e4f8-4480-840d-86cd1787ecf7.png)

**Comment by MeetWq** [comment]
试试现在的行不行

**Comment by LucyChao233** [comment]
可以了
